export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const TOGGLE_TASK = 'TOGGLE_TASK';
export const TOGGLE_LIST_ITEM = 'TOGGLE_LIST_ITEM';
export const LIKE_TASK = 'LIKE_TASK';
export const SET_FILTER = 'SET_FILTER';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const FILTERS = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_FAVORITE: 'SHOW_FAVORITE',
  SHOW_ACTIVE: 'SHOW_ACTIVE',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
};
