export const FETCH_BOARDS_STARTED = 'FETCH_BOARDS_STARTED';
export const FETCH_BOARDS_SUCCESS = 'FETCH_BOARDS_SUCCESS';
export const FETCH_BOARDS_FAILURE = 'FETCH_BOARDS_FAILURE';

export const CREATE_BOARD_STARTED = 'CREATE_BOARD_STARTED';
export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';
export const CREATE_BOARD_FAILURE = 'CREATE_BOARD_FAILURE';

export const EDIT_BOARD_STARTED = 'EDIT_BOARD_STARTED';
export const EDIT_BOARD_SUCCESS = 'EDIT_BOARD_SUCCESS';
export const EDIT_BOARD_FAILURE = 'EDIT_BOARD_FAILURE';

export const DELETE_BOARD_STARTED = 'DELETE_BOARD_STARTED';
export const DELETE_BOARD_SUCCESS = 'DELETE_BOARD_SUCCESS';
export const DELETE_BOARD_FAILURE = 'DELETE_BOARD_FAILURE';

export const FETCH_LISTS_STARTED = 'FETCH_LISTS_STARTED';
export const FETCH_LISTS_SUCCESS = 'FETCH_LISTS_SUCCESS';
export const FETCH_LISTS_FAILURE = 'FETCH_LISTS_FAILURE';

export const CREATE_LIST_STARTED = 'CREATE_LIST_STARTED';
export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS';
export const CREATE_LIST_FAILURE = 'CREATE_LIST_FAILURE';

export const EDIT_LIST_STARTED = 'EDIT_LIST_STARTED';
export const EDIT_LIST_SUCCESS = 'EDIT_LIST_SUCCESS';
export const EDIT_LIST_FAILURE = 'EDIT_LIST_FAILURE';

export const DELETE_LIST_STARTED = 'DELETE_LIST_STARTED';
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';
export const DELETE_LIST_FAILURE = 'DELETE_LIST_FAILURE';

export const FETCH_TASKS_STARTED = 'FETCH_TASKS_STARTED';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';

export const CREATE_TASK_STARTED = 'CREATE_TASK_STARTED';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE';

export const EDIT_TASK_STARTED = 'EDIT_TASK_STARTED';
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
export const EDIT_TASK_FAILURE = 'EDIT_TASK_FAILURE';

export const TOGGLE_TASK_STARTED = 'TOGGLE_TASK_STARTED';
export const TOGGLE_TASK_SUCCESS = 'TOGGLE_TASK_SUCCESS';
export const TOGGLE_TASK_FAILURE = 'TOGGLE_TASK_FAILURE';

export const DELETE_TASK_STARTED = 'DELETE_TASK_STARTED';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE';

export const FETCH_COLORS_STARTED = 'FETCH_COLORS_STARTED';
export const FETCH_COLORS_SUCCESS = 'FETCH_COLORS_SUCCESS';
export const FETCH_COLORS_FAILURE = 'FETCH_COLORS_FAILURE';

export const SET_FILTER = 'SET_FILTER';
export const FILTERS = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_FAVORITE: 'SHOW_FAVORITE',
  SHOW_ACTIVE: 'SHOW_ACTIVE',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
};

export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';

export const SET_COLOR_STARTED = 'SET_COLOR_STARTED';
export const SET_COLOR_SUCCESS = 'SET_COLOR_SUCCESS';
export const SET_COLOR_FAILURE = 'SET_COLOR_FAILURE';

export const COLOR = {
  TRANSPARENT: 'transparent',
  RED: '#f4433650',
  PINK: '#e91e6350',
  PURPLE: '#9c27b050',
  DEEP_PURPLE: '#673ab750',
  BLUE: '#2196f350',
  LIGHT_BLUE: '#00bcd450',
  CYAN: '#00968850',
  GREEN: '#4caf5050',
  LIGHT_GREEN: '#8bc34a50',
  YELLOW: '#ffeb3b50',
  AMBER: '#ffc10750',
  ORANGE: '#ff980050',
  DEEP_ORANGE: '#ff572250',
  GRAY: '#9e9e9e50',
};
