export const FETCH_TASKS_STARTED = 'FETCH_TASKS_STARTED';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';

export const ADD_TASK_STARTED = 'ADD_TASK_STARTED';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAILURE = 'ADD_TASK_FAILURE';

export const DELETE_TASK_STARTED = 'DELETE_TASK_STARTED';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE';

export const TOGGLE_TASK = 'TOGGLE_TASK';
export const TOGGLE_LIST_ITEM = 'TOGGLE_LIST_ITEM';
export const LIKE_TASK = 'LIKE_TASK';

export const SET_FILTER = 'SET_FILTER';
export const FILTERS = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_FAVORITE: 'SHOW_FAVORITE',
  SHOW_ACTIVE: 'SHOW_ACTIVE',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
};

export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
